# 用户输入提示词契约(移植自 /tmp/t1_prompts_backend.py,1.2.13):
# 提取器分型(剔 tool_result/isMeta/local-command/无参命令,/goal 取 command-args)/尾窗 prompts/
# 头扫首条 f:1/uuid 全文端点 _prompt_detail/merge 去重/30 条封顶。
import json
import pathlib
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _util import ck, done

from ccviewer import sessions


def rec(t, content, uuid=None, mid=None, ts=None, **kw):
    d = {'type': t}
    if uuid:
        d['uuid'] = uuid
    if ts:
        d['timestamp'] = ts
    msg = {'content': content}
    if mid:
        msg['id'] = mid
    d['message'] = msg
    d.update(kw)
    return json.dumps(d, ensure_ascii=False)


CMD_GOAL = ('<command-name>/goal</command-name>\n'
            '<command-message>goal</command-message>\n'
            '<command-args>在次会话时,将用户输入的提示词在顶部进行完整的展示,目的是' + '补' * 400 + '</command-args>')
LINES = [
    rec('mode', None),
    rec('user', '<local-command-caveat>Caveat: generated by user</local-command-caveat>', 'u-caveat', isMeta=True),
    rec('user', '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>', 'u-clear'),
    rec('user', CMD_GOAL, 'u-goal', ts='2026-09-05T09:05:32.000Z'),
    rec('user', '<local-command-stdout>Goal set: ……</local-command-stdout>', 'u-stdout'),
    rec('user', 'A session-scoped Stop hook is now active…', 'u-hook', isMeta=True),
    rec('assistant', [{'type': 'text', 'text': '收到目标'}], 'u-a1', mid='msg_a1', ts='2026-09-05T09:06:00.000Z'),
    rec('user', [{'type': 'tool_result', 'tool_use_id': 'x', 'content': 'ok'}], 'u-toolres'),
    rec('user', '第二输入:修等待行截断', 'u-p2', ts='2026-09-05T09:41:07.000Z'),
    rec('assistant', [{'type': 'text', 'text': '好'}], 'u-a2', mid='msg_a2', ts='2026-09-05T09:41:30.000Z'),
    rec('user', '无uuid记录不算', None),
]
BLOB = '\n'.join(LINES) + '\n'

# 1) 提取器分型
ck('extract/plain', sessions._user_prompt(json.loads(LINES[8])) == '第二输入:修等待行截断')
g = sessions._user_prompt(json.loads(LINES[3]))
ck('extract/goal-args', g.startswith('/goal 在次会话时') and '补' * 400 in g and '<command-' not in g, g[:60])
for i, why in [(1, 'caveat'), (2, 'clear无参'), (4, 'stdout'), (5, 'isMeta'), (7, 'tool_result')]:
    d = json.loads(LINES[i])
    ck('extract/skip-' + why, sessions._user_prompt(d) == '', repr(sessions._user_prompt(d))[:60])
ck('extract/assistant', sessions._user_prompt(json.loads(LINES[6])) == '')

# 2) _analyze 尾窗收集 prompts(时间序,摘要≤300,带 uuid/ts)
info = sessions._analyze(BLOB)
ps = info.get('prompts')
ck('analyze/prompts-field', isinstance(ps, list), repr(type(ps)))
if isinstance(ps, list):
    ck('analyze/order', [p['u'] for p in ps] == ['u-goal', 'u-p2'], repr(ps))
    ck('analyze/summary-cap', len(ps[0]['t']) <= 300 and ps[0]['t'].startswith('/goal'), str(len(ps[0]['t'])))
    ck('analyze/ts', ps[1].get('ts') == '2026-09-05T09:41:07.000Z', repr(ps[1]))
    ck('analyze/flag-first-absent', all('f' not in p for p in ps))
    ck('analyze/no-uuid-skipped', all(p['u'] for p in ps) and '无uuid记录不算' not in [p['t'] for p in ps], repr(ps))
ck('analyze/regress-lastPrompt', info['lastPrompt'] == '无uuid记录不算', repr(info['lastPrompt']))
ck('analyze/regress-lastText', info['lastText'] == '好' and info['lastTextMid'] == 'msg_a2')

# 3) 首条(头扫)+ 全文端点 uuid 锚
with tempfile.TemporaryDirectory() as td:
    fp = pathlib.Path(td) / 's.jsonl'
    fp.write_text(BLOB, encoding='utf-8')
    fu, ft, fts = sessions._first_prompt(fp)
    ck('first/uuid+text', fu == 'u-goal' and ft.startswith('/goal') and fts == '2026-09-05T09:05:32.000Z', repr(fu))
    det = sessions._prompt_detail(fp, 'u-goal')
    ck('detail/full-text', det['prompt'].startswith('/goal 在次会话时') and len(det['prompt']) > 300
       and '补' * 400 in det['prompt'], str(len(det.get('prompt', ''))))
    ck('detail/not-miss', not det.get('miss'))
    miss = sessions._prompt_detail(fp, 'deaddead-dead-dead-dead-deaddeaddead')
    ck('detail/miss-flag', miss.get('miss') is True and miss.get('prompt') == '')
    ck('detail/noise-empty', sessions._prompt_detail(fp, 'u-clear').get('miss') is True)
    r1 = sessions._step_detail(fp, 'msg_a2')
    ck('route/assistant-step-kept', r1['result'] == '好' or r1['prompt'] != '', repr(r1))

# 4) 组装:尾窗已含首条 → 不重复补;不含 → 挂 f:1 置顶
tail1 = [{'u': 'u-goal', 't': '/goal …', 'ts': 'T'}, {'u': 'u-p2', 't': '第二', 'ts': 'T'}]
out = sessions._merge_prompts(tail1, ('u-goal', 'x', 'T'))
ck('merge/dedup', [p['u'] for p in out] == ['u-goal', 'u-p2'] and 'f' not in out[0], repr(out))
out2 = sessions._merge_prompts([{'u': 'u-p2', 't': '第二', 'ts': 'T'}], ('u-goal', '/goal 全文头', 'T'))
ck('merge/prepend-first', out2[0] == {'u': 'u-goal', 't': '/goal 全文头', 'ts': 'T', 'f': 1}, repr(out2))
ck('merge/only-first', sessions._merge_prompts([], ('u-a', 'a', ''))[0].get('f') == 1)
ck('merge/no-first', sessions._merge_prompts([{'u': 'z', 't': '', 'ts': ''}], ('', '', '')) == [{'u': 'z', 't': '', 'ts': ''}])

# 5) 尾窗上限:30 条封顶取最近
big = '\n'.join(rec('user', '输入%03d' % i, 'ub%02d' % i) for i in range(45))
infob = sessions._analyze(big)
ck('cap/30-newest', len(infob['prompts']) == 30 and infob['prompts'][-1]['t'] == '输入044'
   and infob['prompts'][0]['t'] == '输入015', str(len(infob['prompts'])))

done()
